# Configurations
title: tdTomato's Blog
# longtitle:
author: tdTomato
# email:
description: >
  tdTomato's Blog

version: 1.0
gitbook_version: 3.2.3

url: "https://tdtomato.github.io"
baseurl: ""
rss: RSS

# bootstrap: use the remote theme for the site itself
remote_theme: sighingnow/jekyll-gitbook

github_username: tdtomato
twitter_username: tdTomato628

toc:
  enabled: false
  # h_min: 1
  # h_max: 3

# customize the link favicon in header, will be {{site.baseurl}}/{{site.favicon_path}}
favicon_path: /assets/images/favicon.ico

# markdown render engine.
markdown: kramdown
kramdown:
  auto_ids: true
  input: GFM
  math_engine: mathjax
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  toc_levels: 1..6
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    guess_lang: true

syntax_highlighter_style: colorful

markdown_ext: markdown,mkdown,mkdn,mkd,md

# Disqus comments
# disqushandler:            sighingnow

exclude:
  - _drafts

collections:
  posts:
    output: true
    permalink: /:categories/:year-:month-:day-:title:output_ext
    sort_by: date
  pages:
    output: true
    permalink: /:collection/:path
  scraps:
    output: true
    permalink: /:collection/:path

ordered_collections:
  - pages
  - scraps
  - posts

page_width: 800px

destination: ./_site
incremental: false
regenerate: true

plugins:
  - jekyll-feed
  - jekyll-readme-index
  - jemoji
